### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by noblejasper** [probablycorey/visual-bell#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/visual-bell/lib/visual-bell.coffee:8:9)
```

**Comment by probablycorey** [comment]
Thanks for reporting this @noblejasper, I'll take care of it tomorrow!

**Comment by noblejasper** [comment]
:+1: Thanks!
